# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7ec9c8974569e90c28005f7b3d3b86f7b3651d4f16d67d9df90c8e025071d090ed9d54c6cceac572945d28d8460e7f475129ccc5cb0d4ce9d09aef649419c02

test:
  secret_key_base: 82478509b9502d1ff46c151890f97cf9dae2ddd4a8f5e5a039416de38aeab398e773991c5d643e8d2f07dffe837c6034ac216c532f065414a6149f0c9e36b2ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
